# Install script for directory: /NOBACKUP/davoudss/gromacs-4.6.1/scripts

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/NOBACKUP/davoudss/gromacs")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")
  list(APPEND CPACK_ABSOLUTE_DESTINATION_FILES
   "/NOBACKUP/davoudss/gromacs/bin/GMXRC")
FILE(INSTALL DESTINATION "/NOBACKUP/davoudss/gromacs/bin" TYPE PROGRAM FILES "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/GMXRC")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")
  list(APPEND CPACK_ABSOLUTE_DESTINATION_FILES
   "/NOBACKUP/davoudss/gromacs/bin/GMXRC.bash")
FILE(INSTALL DESTINATION "/NOBACKUP/davoudss/gromacs/bin" TYPE PROGRAM FILES "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/GMXRC.bash")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")
  list(APPEND CPACK_ABSOLUTE_DESTINATION_FILES
   "/NOBACKUP/davoudss/gromacs/bin/GMXRC.zsh")
FILE(INSTALL DESTINATION "/NOBACKUP/davoudss/gromacs/bin" TYPE PROGRAM FILES "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/GMXRC.zsh")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")
  list(APPEND CPACK_ABSOLUTE_DESTINATION_FILES
   "/NOBACKUP/davoudss/gromacs/bin/GMXRC.csh")
FILE(INSTALL DESTINATION "/NOBACKUP/davoudss/gromacs/bin" TYPE PROGRAM FILES "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/GMXRC.csh")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")
  list(APPEND CPACK_ABSOLUTE_DESTINATION_FILES
   "/NOBACKUP/davoudss/gromacs/bin/completion.csh;/NOBACKUP/davoudss/gromacs/bin/completion.zsh;/NOBACKUP/davoudss/gromacs/bin/completion.bash")
FILE(INSTALL DESTINATION "/NOBACKUP/davoudss/gromacs/bin" TYPE FILE FILES
    "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/completion.csh"
    "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/completion.zsh"
    "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/completion.bash"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")
  list(APPEND CPACK_ABSOLUTE_DESTINATION_FILES
   "/NOBACKUP/davoudss/gromacs/bin/demux.pl")
FILE(INSTALL DESTINATION "/NOBACKUP/davoudss/gromacs/bin" TYPE PROGRAM FILES "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/demux.pl")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")
  list(APPEND CPACK_ABSOLUTE_DESTINATION_FILES
   "/NOBACKUP/davoudss/gromacs/bin/xplor2gmx.pl")
FILE(INSTALL DESTINATION "/NOBACKUP/davoudss/gromacs/bin" TYPE PROGRAM FILES "/NOBACKUP/davoudss/gromacs-4.6.1/scripts/xplor2gmx.pl")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "scripts")

